[project]
name = "SimpleCalculator"
version = "1.0.0"
description = "Simple Python CLI calculator with variables and user-defined functions support."
requires-python = ">=3.10"
dependencies = [
    "pre-commit>=4.3.0",
]
